# Generated by Django 3.1.2 on 2020-10-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinfo',
            options={'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='doc_first_page',
            field=models.FileField(upload_to='upload', verbose_name='Разворот с фото'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='doc_second_page',
            field=models.FileField(upload_to='upload', verbose_name='Разворот с регистрацией'),
        ),
        migrations.CreateModel(
            name='PlatformRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read_rule', models.BooleanField(default=False, verbose_name='Ознакомился с правилами')),
                ('is_ru_tax_resident', models.BooleanField(default=False, verbose_name='Налоговый резидент РФ')),
                ('consent_to_use_auto_completion', models.BooleanField(default=False, verbose_name='Согласие использовать автопополнение')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.clientinfo')),
            ],
            options={
                'verbose_name_plural': 'Правила платформы',
            },
        ),
    ]
