# Generated by Django 3.1.2 on 2020-10-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201024_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformrule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rule', to='api.clientinfo'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_economist', models.BooleanField(default=False, verbose_name='Высшее экономическое')),
                ('total_cost_more_six_ml', models.BooleanField(default=False, verbose_name='Общая стоимость более 6 млн')),
                ('experience_in_fintech', models.BooleanField(default=False, verbose_name='Опыт работы в финансовой компании')),
                ('deposit_more_six_ml', models.BooleanField(default=False, verbose_name='Депозит более 6 млн')),
                ('active_trade_more_six_ml', models.BooleanField(default=False, verbose_name='Активная торговля более 6 млн')),
                ('already_qualified', models.BooleanField(default=False, verbose_name='Уже квалифицирован')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_qualification', to='api.clientinfo')),
            ],
        ),
    ]
