# Generated by Django 3.1.2 on 2020-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201024_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='active_trade_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Активная торговля более 6 млн'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='already_qualified',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='же квалифицирован'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='deposit_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Депозит более 6 млн'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='experience_in_fintech',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Опыт работы в финансовой компании'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='is_economist',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Высшее экономическое'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='total_cost_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Общая стоимость более 6 млн'),
        ),
    ]
