# Generated by Django 3.1.2 on 2020-10-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201024_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='doc_first_page',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='doc_second_page',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='already_qualified',
            field=models.FileField(blank=True, null=True, upload_to='upload/Qualification', verbose_name='Уже квалифицирован'),
        ),
        migrations.CreateModel(
            name='ClientPersDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_page', models.FileField(upload_to='upload', verbose_name='Разворот с фото')),
                ('doc_second_page', models.FileField(upload_to='upload', verbose_name='Разворот с регистрацией')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_pers_doc', to='api.clientinfo')),
            ],
        ),
    ]
