# Generated by Django 3.1.2 on 2020-10-24 14:16

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201024_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpersdoc',
            options={'verbose_name_plural': 'Документы клиента'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name_plural': 'Квалификация'},
        ),
        migrations.AlterField(
            model_name='clientpersdoc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_pers_doc', to='api.clientinfo', unique=True),
        ),
        migrations.AlterField(
            model_name='clientpersdoc',
            name='doc_first_page',
            field=models.FileField(upload_to=api.models.get_upload_path, verbose_name='Разворот с фото'),
        ),
        migrations.AlterField(
            model_name='clientpersdoc',
            name='doc_second_page',
            field=models.FileField(upload_to=api.models.get_upload_path, verbose_name='Разворот с регистрацией'),
        ),
        migrations.AlterField(
            model_name='platformrule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rule', to='api.clientinfo', unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='active_trade_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Активная торговля более 6 млн'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='already_qualified',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Уже квалифицирован'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_qualification', to='api.clientinfo', unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='deposit_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Депозит более 6 млн'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='experience_in_fintech',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Опыт работы в финансовой компании'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='is_economist',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Высшее экономическое'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='total_cost_more_six_ml',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, verbose_name='Общая стоимость более 6 млн'),
        ),
        migrations.CreateModel(
            name='ClientState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_qualified', models.BooleanField(default=False, verbose_name='Квалифицирован')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_state', to='api.clientinfo', unique=True)),
            ],
        ),
    ]
